/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 japanese_room.glb 
Author: YANGGA (https://sketchfab.com/YANGGA)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-room-2561ec6948a44edd87650f3a454e3722
Title: Japanese Room
*/

import { useGLTF, useTexture } from '@react-three/drei'
import { EffectComposer, SelectiveBloom } from '@react-three/postprocessing';
import * as THREE from 'three'
import { useRef } from 'react';
import { BlendFunction } from 'postprocessing';

export function Japanese(props) {
  const matcapTexture = useTexture("/images/textures/mat1.png");
  const { nodes, materials } = useGLTF('/models/japanese_room.glb');
  const screensRef = useRef();

  const curtainMaterial = new THREE.MeshPhongMaterial({ color: "#d90429" }) // menambahkan material warna
  const bodyMaterial = new THREE.MeshPhongMaterial({ map: matcapTexture }) // menambahkan material tekstur

  return (
    <group {...props} dispose={null}>

      <EffectComposer>
        <SelectiveBloom 
          selection={screensRef}
          intensity={1}
          luminanceThreshold={0.2}
          luminanceSmoothing={0.9}
          blendFunction={BlendFunction.ADD}
        />
      </EffectComposer>

      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={curtainMaterial} />
        <mesh geometry={nodes.Object_3.geometry} material={bodyMaterial} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.katana_1} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.katana_2} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.milk} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.texture} ref={screensRef}/>
        <mesh geometry={nodes.Object_8.geometry} material={materials.GREY} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.black} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.brown} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.dark_blue} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.dark_brown} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.green} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.light_green} />
        <mesh geometry={nodes.Object_17.geometry} material={materials['table.001']} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.teh_pot} />
        <mesh geometry={nodes.Object_19.geometry} material={materials.wall} />
        <mesh geometry={nodes.Object_20.geometry} material={materials.white} />
        <mesh geometry={nodes.Object_21.geometry} material={materials.yellow} />
      </group>
    </group>
  )
}

useGLTF.preload('/models/japanese_room.glb')
